-- ==========================================================
-- Railway Ticket Booking System - Seed Data (DML)
-- ==========================================================

-- 1. SEED USERS
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD, PHONE, ROLE)
VALUES ('Admin User', 'admin@railway.com', 'admin123', '9876543210', 'ADMIN');

INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD, PHONE, ROLE)
VALUES ('Yashi Saxena', 'yashi@example.com', 'Yashi@123', '9123456780', 'USER');

INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD, PHONE, ROLE)
VALUES ('Rahul Sharma', 'rahul@example.com', 'rahul123', '9988776655', 'USER');

-- 2. SEED TRAINS
INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Vande Bharat Express', '22436', 'New Delhi', 'Varanasi', '06:00 AM', '02:00 PM', 1750.00, 120, 115, 'Vande Bharat');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Rajdhani Express', '12952', 'New Delhi', 'Mumbai', '04:55 PM', '08:35 AM', 2450.00, 150, 142, 'Superfast Express');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Shatabdi Express', '12002', 'New Delhi', 'Bhopal', '06:00 AM', '02:40 PM', 1350.00, 100, 96, 'Superfast');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Duronto Express', '12260', 'Mumbai', 'Howrah', '05:15 PM', '08:15 PM', 2800.00, 140, 138, 'Duronto');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Bangalore Express', '12628', 'New Delhi', 'Bengaluru', '08:00 PM', '06:45 AM', 2100.00, 150, 145, 'Express');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Chennai Mail', '12602', 'Mumbai', 'Chennai', '10:30 PM', '04:00 AM', 1850.00, 120, 118, 'Mail');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Golden Temple Mail', '12903', 'Mumbai', 'Amritsar', '06:45 PM', '05:30 AM', 1650.00, 130, 124, 'Superfast');

INSERT INTO TRAINS (TRAIN_NAME, TRAIN_NUMBER, SOURCE_STATION, DESTINATION_STATION, DEPARTURE_TIME, ARRIVAL_TIME, FARE, TOTAL_SEATS, AVAILABLE_SEATS, TRAIN_TYPE)
VALUES ('Vande Bharat Express', '20834', 'Howrah', 'Puri', '06:10 AM', '12:35 PM', 1420.00, 100, 98, 'Vande Bharat');

-- 3. SEED BOOKINGS
INSERT INTO BOOKINGS (PNR, PASSENGER_NAME, JOURNEY_DATE, COACH, SEAT_NUMBER, PASSENGERS, TOTAL_AMOUNT, BOOKING_STATUS, USER_ID, TRAIN_ID)
VALUES ('8472910482', 'Yashi Saxena', TO_DATE('2026-10-15', 'YYYY-MM-DD'), 'B2', 'B2-24', 1, 2450.00, 'CONFIRMED', 2, 2);

INSERT INTO BOOKINGS (PNR, PASSENGER_NAME, JOURNEY_DATE, COACH, SEAT_NUMBER, PASSENGERS, TOTAL_AMOUNT, BOOKING_STATUS, USER_ID, TRAIN_ID)
VALUES ('6294018371', 'Rahul Sharma', TO_DATE('2026-10-20', 'YYYY-MM-DD'), 'C1', 'C1-18', 1, 1750.00, 'CONFIRMED', 3, 1);

-- 4. SEED PAYMENTS
INSERT INTO PAYMENTS (BOOKING_ID, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, TRANSACTION_ID)
VALUES (1, 2450.00, 'SUCCESS', 'UPI', 'TXN_ORCL_8472910482');

INSERT INTO PAYMENTS (BOOKING_ID, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, TRANSACTION_ID)
VALUES (2, 1750.00, 'SUCCESS', 'Debit Card', 'TXN_ORCL_6294018371');

COMMIT;
