# Server Port
server.port=8081

# Oracle Database Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=system
spring.datasource.password=Yashi@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true